backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "homepage"
    label: "Homepage Content"
    files:
      - file: "index.html"
        label: "Homepage"
        name: "home"
        fields:
          - label: "Hero Title"
            name: "hero_title"
            widget: "string"
          - label: "Hero Paragraph"
            name: "hero_paragraph"
            widget: "text"
          - label: "Vision Title"
            name: "vision_title"
            widget: "string"
          - label: "Vision Paragraph"
            name: "vision_paragraph"
            widget: "text"
          - label: "Challenge Title"
            name: "challenge_title"
            widget: "string"
          - label: "Challenge Paragraph"
            name: "challenge_paragraph"
            widget: "text"
          - label: "Revolution Title"
            name: "revolution_title"
            widget: "string"
          - label: "Revolution Paragraph"
            name: "revolution_paragraph"
            widget: "text"
          - label: "CTA Paragraph 1"
            name: "cta_1"
            widget: "text"
          - label: "CTA Paragraph 2"
            name: "cta_2"
            widget: "text"
          - label: "CTA Button Text"
            name: "cta_button"
            widget: "string"
